# Generated by Django 5.2.3 on 2025-10-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.ForeignKey(blank=True, db_column='id_career', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Career.career')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
    ]
