# Generated by Django 5.2.3 on 2025-10-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id_career', models.AutoField(primary_key=True, serialize=False)),
                ('career_name', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('career_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.ForeignKey(db_column='id_fac', on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty')),
            ],
        ),
    ]
